# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60ff2e89ea0dd8b0659ade1c0da2b967242b6af4e23beef1720ce2fe85110ba48a4eaa1ecf626448f979c1c4d472481ab5efeb5de6ff22514a8d42c6ff03834f

test:
  secret_key_base: 0598a80f4dca6435c5267b8c13d4a38224418df6bbba23e0ad0464cfb2923494bbba0cad6cf2958c39ab7292ea34634157ca34682fc5185435c541f7870d9a40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
